name: dento_support
description: A new Flutter project.

publish_to: "none"

# iOS -> 0.1.0+11
# Android -> 0.1.0+4
version: 1.0.4+11

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.8
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  go_router: ^6.0.3
  grouped_list: ^5.1.2
  intl: ^0.18.0
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.2
  pinput: ^2.2.20
  popover: ^0.2.8
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15
  stream_transform: ^2.1.0
  url_launcher: ^6.1.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.0.15
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/treatments/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
